version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=c@lculus2689"
            - "MYSQL_DATABASE=dockerapp"
        ports:
            - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - "MYSQL_USERNAME=root"
            - "MYSQL_ROOT_PASSWORD=c@lculus2689"
            - "PMA_HOST=database"
        links:
            - database
        ports:
            - "8000:80"